baseURL = "https://betterthantomorrow.top/"
languageCode = "en"
theme = "hugo-theme-stack"
defaultContentLanguage = "en"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "做自己想做的事情，从新出发，从心出发Follow your heart"
  author = "Follow your heart"
  keywords = ["blog", "Follow your heart", "study","博客","学习"]
  googleAnalytics = "G-CRJBCH6L08"
# 1
[languages]
  [languages.en]
    languageName = "English"
    title = "WJ-English"
    weight = 1
    contentDir = "content/en"
    [languages.en.params.sidebar]
      emoji = "🍥"
      subtitle = "Unity of Knowledge and Action"
    
  [languages.zh-cn]
    languageName = "简体中文"
    title = "WJ-中文"
    weight = 1
    contentDir = "content/zh-cn"
    [languages.zh-cn.params.sidebar]
      emoji = "🍥"
      subtitle = "知行合一"