baseURL = "https://betterthantomorrow.top/"
languageCode = "zh-cn"
title = "Fllow your heart"
theme = "hugo-theme-stack"

[languages]
  [languages.en]
    languageName = "English"
    title = "Fllow your heart"
    weight = 1
    [languages.en.params.sidebar]
      emoji = "🍥"
      subtitle = "Unity of Knowledge and Action"
    
  [languages.zh-cn]
    languageName = "简体中文"
    title = "从心出发"
    weight = 2
    [languages.zh-cn.params.sidebar]
      emoji = "🍥"
      subtitle = "知行合一"