baseURL = "https://betterthantomorrow.top/"
languageCode = "zh-cn"
title = "子小言记t"
theme = "hugo-theme-stack"
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "做自己想做的事情，从新出发，从心出发Follow your heart"
  author = "Follow your heart"
  keywords = ["blog", "Follow your heart", "study","博客","学习","从心出发"]
  googleAnalytics = "G-RQMNSJDBE2"
  enableGoogleAds = true
  googleAdsScriptSrc = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4851827946087899"
  [params.Author]
    name = "Your Name"
    email = "your-email@example.com"

[languages]
  [languages.en]
    languageName = "English"
    title = "子小言记"
    weight = 1
    [languages.en.params.sidebar]
      emoji = "🍥"
      subtitle = "Unity of Knowledge and Action"
    
  [languages.zh-cn]
    languageName = "简体中文"
    title = "子小言记"
    weight = 2
    [languages.zh-cn.params.sidebar]
      emoji = "🍥"
      subtitle = "知行合一"

